### PR TITLE
Django settings import correction, xlrd setup dependancy

### PR DESCRIPTION
**Pull request by ashishnitinpatil**

### CODE REVIEW

**Comment by ashishnitinpatil** [comment]
I have not tested the setup.py after the dependency addition.

**Comment by ashishnitinpatil** [comment]
Sorry, this is not working. I'll come up with a working fix on it. Will issue new pull request.

**Comment by pstch** [comment]
I didn't really work on this project recently, as I focused on django-import-export.

batchimport (i'm not the original author) is still a really neat piece of code, and I think a very good reusable app for data import/export could be made from it, but it requires time (that I don't have right now, as I work a lot on @pstch/django-crucrudile).

I'll be happy to review your PRs and help/work with you if you start working on django-batchimport :)

**Comment by ashishnitinpatil** [comment]
Thanks, but I didn't do much. I did it get it working though. You can check my forked repo for the fixes - https://github.com/ashishnitinpatil/django-batchimport/

**Pull request closed without merging**
